### ISSUE TITLE
adminserver 安装board是， ssh端口不是22时， 安装board失败

### ISSUE THREAD

**Issue by guyingyan** [inspursoft/board#1772]
adminserver 安装board是， ssh端口不是22时， 安装board失败

**Comment by guyingyan** [comment]
![image](https://user-images.githubusercontent.com/33680763/123218655-91ede200-d4fe-11eb-85da-31188ea928a8.png)

**Comment by JackZxj** [comment]
The reason is that the host's security configuration disabled the SSH PasswordAuthentication, and the code only supports PasswordAuthentication. I will fix this bug later.
