### ISSUE TITLE
too many "pause" containers in the edgenode

### ISSUE THREAD

**Issue by inspuradmin** [inspursoft/board#877]
In GitLab by @luotian-github on Jul 15, 2020, 14:34

3 pods

![image](/uploads/a434acdc9a1fa2f9c4e82ac2e4908ecf/image.png)

alots of pause

![image](/uploads/b7b66433ec3cd7818245a554445c06e5/image.png)

**Comment by inspuradmin** [comment]
In GitLab by @luotian-github on Jul 15, 2020, 14:34

assigned to @tmon546596046

**Comment by inspuradmin** [comment]
In GitLab by @tmon546596046 on Sep 8, 2020, 09:04

as kubernetes dockershim code:


```
func makeContainerName(s *runtimeapi.PodSandboxConfig, c *runtimeapi.ContainerConfig) string {
	return strings.Join([]string{
		kubePrefix,                            // 0
		c.Metadata.Name,                       // 1:
		s.Metadata.Name,                       // 2: sandbox name
		s.Metadata.Namespace,                  // 3: sandbox namesapce
		s.Metadata.Uid,                        // 4  sandbox uid
		fmt.Sprintf("%d", c.Metadata.Attempt), // 5
	}, nameDelimiter)
}
```

you will see the sandbox name(pause) changes
for example:  
prometheus-node-exporter-6pmw9  
prometheus-node-exporter-zslx9  
prometheus-node-exporter-89c45  
prometheus-node-exporter-tfpkd  

we should check the edge hub for message recieved.

**Comment by luotian-github** [comment]
closed, not issued
